# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: Default

steps:
- task: CacheBeta@0
  inputs:
    key: 'hello123'
    path: 'D:\_temp\gfdg'